### ISSUE TITLE
Implement state preserving of daemon process

### ISSUE THREAD

**Issue by RajithaKumara** [teamellipsis/migratory-skeleton-app#4]

**Comment by RajithaKumara** [comment]
Fail to get `count` variable from `vm` `sandbox` without defining.
```
ReferenceError: count is not defined
    at getCount (evalmachine.<anonymous>:169:5)
    at app.post (evalmachine.<anonymous>:99:34)
    at Layer.handle [as handle_request] (./migratory-skeleton-app/node_modules/express/lib/router/layer.js:95:5)
    at next (./migratory-skeleton-app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (./migratory-skeleton-app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (./migratory-skeleton-app/node_modules/express/lib/router/layer.js:95:5)
    at ./migratory-skeleton-app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (./migratory-skeleton-app/node_modules/express/lib/router/index.js:335:12)
    at next (./migratory-skeleton-app/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (./migratory-skeleton-app/node_modules/body-parser/lib/types/urlencoded.js:82:7)
```

**Comment by RajithaKumara** [comment]
> Fail to get `count` variable from `vm` `sandbox` without defining.
> 
> ```
> ReferenceError: count is not defined
>     at getCount (evalmachine.<anonymous>:169:5)
>     at app.post (evalmachine.<anonymous>:99:34)
>     at Layer.handle [as handle_request] (./migratory-skeleton-app/node_modules/express/lib/router/layer.js:95:5)
>     at next (./migratory-skeleton-app/node_modules/express/lib/router/route.js:137:13)
>     at Route.dispatch (./migratory-skeleton-app/node_modules/express/lib/router/route.js:112:3)
>     at Layer.handle [as handle_request] (./migratory-skeleton-app/node_modules/express/lib/router/layer.js:95:5)
>     at ./migratory-skeleton-app/node_modules/express/lib/router/index.js:281:22
>     at Function.process_params (./migratory-skeleton-app/node_modules/express/lib/router/index.js:335:12)
>     at next (./migratory-skeleton-app/node_modules/express/lib/router/index.js:275:10)
>     at urlencodedParser (./migratory-skeleton-app/node_modules/body-parser/lib/types/urlencoded.js:82:7)
> ```
